language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false

node_js:
  - 'stable'
  - '12'
  - '10'
  - '8'

# Lint errors should trigger a failure.
before_script:
  - npm run lint:ci
  - npm run build

# Runs the coverage script (which runs the tests)
script: npm run coveralls
